---
- name: Add a new network adapter to a VM
  hosts: localhost
  gather_facts: false
  collections:
    - community.postgresql

  vars:
    vm_id: "{{ vm_id | default('') }}"
    process_instance_id: "{{ process_instance_id | default('') }}"

  tasks:
    - name: Debug empfangene Variablen aus extra_vars
      debug:
        msg:
          - "✅ VM ID: {{ vm_id }}"
          - "✅ Prozess-Instance-ID: {{ process_instance_id }}"

    - name: Validate input variables
      fail:
        msg: "❌ Fehlende Variablen! vm_id={{ vm_id }}, process_instance_id={{ process_instance_id }}"
      when: 
        - vm_id | trim == "" 
        - process_instance_id | trim == ""

    - block:
        - name: Add network adapter entry to the database
          community.postgresql.postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            login_host: "10.0.2.15"
            login_port: 5432
            query: "INSERT INTO Netzwerkadapter (vm_id) VALUES ({{ vm_id }})"
          register: result

        - name: Erfolgreich hinzugefügt
          debug:
            msg: "✅ Netzwerkadapter erfolgreich hinzugefügt für VM ID {{ vm_id }}"

        - name: Erfolgreiche Änderung an Camunda melden
          uri:
            url: "http://10.0.2.15:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "add_network_completed"
              processInstanceId: "{{ process_instance_id }}"
            status_code: 204

      rescue:
        - name: Fehler an Camunda melden
          uri:
            url: "http://10.0.2.15:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "add_network_failed"
              processInstanceId: "{{ process_instance_id }}"
            status_code: 204

        - name: Log failure message
          debug:
            msg: "❌ Netzwerkadapter-Update fehlgeschlagen für VM ID {{ vm_id }}. Fehler an Camunda gesendet."
