---
- name: Add a new network adapter to a VM
  hosts: localhost
  gather_facts: false
  collections:
    - community.postgresql
  vars:
    vm_id: null # Dynamisch übergebene VM-ID
  tasks:
    - name: Validate input variables
      fail:
        msg: "vm_id must be provided"
      when: vm_id is not defined

    - block:
        - name: Add network adapter entry to the database
          community.postgresql.postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            query: "INSERT INTO Netzwerkadapter (vm_id) VALUES ({{ vm_id }})"
          register: result

        - name: Signal successful completion to Camunda
          when: result.failed is not defined or not result.failed
          uri:
            url: "http://localhost:8080/engine-rest/signal"
            method: POST
            headers:
              Content-Type: "application/json"
            body: |
              {
                "name": "network_add_completed",
                "processVariables": {
                  "vm_id": { "value": "{{ vm_id }}", "type": "String" },
                  "job_status": { "value": "success", "type": "String" }
                }
              }
            body_format: json
            status_code: 204

      rescue:
        - name: Signal failure to Camunda
          uri:
            url: "http://localhost:8080/engine-rest/signal"
            method: POST
            headers:
              Content-Type: "application/json"
            body: |
              {
                "name": "network_add_failed",
                "processVariables": {
                  "vm_id": { "value": "{{ vm_id }}", "type": "String" },
                  "error_message": { "value": "Failed to add network adapter for VM ID {{ vm_id }}", "type": "String" }
                }
              }
            body_format: json
            status_code: 204

        - name: Log failure message
          debug:
            msg: "Failed to add network adapter for VM ID {{ vm_id }}. Signal sent to Camunda."
