---
- name: Add a new disk to a VM
  hosts: localhost
  gather_facts: false
  collections:
    - community.postgresql

  vars:
    vm_id: null
    disk_size: null
    process_instance_id: null

  tasks:
    - name: Validate input variables
      fail:
        msg: "vm_id, disk_size, and process_instance_id must be provided"
      when: vm_id is not defined or disk_size is not defined or process_instance_id is not defined

    - block:
        - name: Add disk entry to the database
          community.postgresql.postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            query: "INSERT INTO Disks (vm_id, disk_size) VALUES ({{ vm_id }}, {{ disk_size }})"
          register: result

        - name: Confirm disk addition
          debug:
            msg: "Disk added successfully to VM ID {{ vm_id }}"

        - name: Signal successful completion to Camunda
          uri:
            url: "http://localhost:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "storage_add_completed"
              processInstanceId: "{{ process_instance_id }}"
            status_code: 204

      rescue:
        - name: Signal failure to Camunda
          uri:
            url: "http://localhost:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "storage_add_failed"
              processInstanceId: "{{ process_instance_id }}"
            status_code: 204

        - name: Log failure message
          debug:
            msg: "Failed to add storage for VM ID {{ vm_id }}. Signal sent to Camunda."
