---
- name: Change RAM size for a VM
  hosts: localhost
  gather_facts: false
  collections:
    - community.postgresql

  vars:
    vm_id: "{{ vm_id }}"
    value: "{{ value }}"
    process_instance_id: "{{ process_instance_id }}"

  tasks:
    - name: Debug empfangene Variablen aus extra_vars
      debug:
        msg:
          - "✅ VM ID: {{ vm_id }}"
          - "✅ Neuer RAM-Wert: {{ value }} GB"
          - "✅ Prozess-Instance-ID: {{ process_instance_id }}"

    - name: Debug API Request Body
      debug:
        msg:
          - "✅ processInstanceId: {{ process_instance_id }}"
          - "✅ value (CPU-Wert): {{ value }} (Typ: {{ value | type_debug }})"


    - name: Validate input variables
      fail:
        msg: "❌ Fehlende Variablen! vm_id={{ vm_id }}, value={{ value }}, process_instance_id={{ process_instance_id }}"
      when: 
        - vm_id | trim == "" 
        - value | trim == "" 
        - process_instance_id | trim == ""

    - block:
        - name: Update RAM size in der Datenbank
          community.postgresql.postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            login_host: "10.0.2.15"
            login_port: 5432
            query: "UPDATE VMs SET ram_size = {{ value | int }} WHERE vm_id = {{ vm_id | int }}"
          register: result

        - name: Erfolgreich aktualisiert
          debug:
            msg: "✅ RAM erfolgreich geändert für VM ID {{ vm_id }} auf {{ value }} GB"

        - name: Erfolgreiche Änderung an Camunda melden
          uri:
            url: "http://10.0.2.15:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "ram_change_completed"
              processInstanceId: {{ process_instance_id }}
            status_code: 204

      rescue:
        - name: Fehler an Camunda melden
          uri:
            url: "http://10.0.2.15:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "ram_change_failed"
              processInstanceId: {{ process_instance_id }}
            status_code: 204

        - name: Log failure message
          debug:
            msg: "❌ RAM-Update fehlgeschlagen für VM ID {{ vm_id }}. Fehler an Camunda gesendet."
