---
- name: Einfaches Playbook für Testzwecke
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Testausgabe anzeigen
      debug:
        msg: "Das Playbook: "change_cpu.yaml" wurde erfolgreich ausgeführt!"
