---
- name: Change CPU count for a VM
  hosts: localhost
  gather_facts: false
  collections:
    - community.postgresql

  vars:
    vm_id: "{{ vm_id }}"
    value: "{{ value }}"
    process_instance_id: "{{ process_instance_id }}"

  tasks:
    - name: Debug empfangene Variablen aus extra_vars
      debug:
        msg:
          - "✅ VM ID: {{ vm_id }}"
          - "✅ Neuer CPU-Wert: {{ value }}"
          - "✅ Prozess-Instance-ID: {{ process_instance_id }}"

    - name: Debug API Request Body
      debug:
        msg:
          - "✅ processInstanceId: {{ process_instance_id }}"
          - "✅ value (CPU-Wert): {{ value }} (Typ: {{ value | type_debug }})"

    - name: Validate input variables
      fail:
        msg: "❌ Fehlende Variablen! vm_id={{ vm_id }}, value={{ value }}, process_instance_id={{ process_instance_id }}"
      when: 
        - vm_id | trim == "" 
        - value | trim == "" 
        - process_instance_id | trim == ""

    - block:
        - name: Update CPU count in der Datenbank
          community.postgresql.postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            login_host: "10.0.2.15"
            login_port: 5432
            query: "UPDATE VMs SET cpu_count = {{ value | int }} WHERE vm_id = {{ vm_id | int }}"
          register: result

        - name: Erfolgreich aktualisiert
          debug:
            msg: "✅ CPU erfolgreich geändert für VM ID {{ vm_id }} auf {{ value }} Kerne"

        - name: Debug final API Request an Camunda
          debug:
            msg:
              - "📤 Camunda API Request:"
              - "🔹 URL: http://10.0.2.15:8080/engine-rest/message"
              - "🔹 messageName: cpu_change_completed"
              - "🔹 processInstanceId: {{ process_instance_id }}"
              - "🔹 value: {{ value }} (Typ: {{ value | type_debug }})"

        - name: Erfolgreiche Änderung an Camunda melden
          uri:
            url: "http://10.0.2.15:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "cpu_change_completed"
              processInstanceId: "{{ process_instance_id }}"
              processVariables:
                value:
                  value: "{{ value | int }}"
                  type: "Integer"
            status_code: 204


      rescue:
        - name: Fehler an Camunda melden
          uri:
            url: "http://10.0.2.15:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "cpu_change_failed"
              processInstanceId: "{{ process_instance_id }}"
              variables:
                vm_id:
                  value: "{{ vm_id }}"
                  type: "Integer"
                value:
                  value: "{{ value }}"
                  type: "Integer"
            status_code: 204

        - name: Log failure message
          debug:
            msg: "❌ CPU-Update fehlgeschlagen für VM ID {{ vm_id }}. Fehler an Camunda gesendet."
