---
- name: Change CPU count for a VM
  hosts: localhost
  gather_facts: false
  collections:
    - community.postgresql
  vars:
    vm_id: null         # Dynamisch übergebene VM-ID
    new_cpu_count: null # Dynamisch übergebene CPU-Anzahl
  tasks:
    - name: Validate input variables
      fail:
        msg: "vm_id and new_cpu_count must be provided"
      when: vm_id is not defined or new_cpu_count is not defined

    - block:
        - name: Update CPU count in the database
          postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            query: "UPDATE VMs SET cpu_count = {{ new_cpu_count }} WHERE vm_id = {{ vm_id }}"
          register: result

        - name: Signal successful completion to Camunda
          when: result.failed is not defined or not result.failed
          uri:
            url: "http://localhost:8080/engine-rest/signal"
            method: POST
            headers:
              Content-Type: "application/json"
            body: |
              {
                "name": "cpu_change_completed",
                "processVariables": {
                  "vm_id": { "value": "{{ vm_id }}", "type": "String" },
                  "cpu_count": { "value": "{{ new_cpu_count }}", "type": "Integer" },
                  "job_status": { "value": "success", "type": "String" }
                }
              }
            body_format: json
            status_code: 204

      rescue:
        - name: Signal failure to Camunda
          uri:
            url: "http://localhost:8080/engine-rest/signal"
            method: POST
            headers:
              Content-Type: "application/json"
            body: |
              {
                "name": "cpu_change_failed",
                "processVariables": {
                  "vm_id": { "value": "{{ vm_id }}", "type": "String" },
                  "error_message": { "value": "Failed to update CPU count for VM ID {{ vm_id }}", "type": "String" }
                }
              }
            body_format: json
            status_code: 204

        - name: Log failure message
          debug:
            msg: "CPU update failed for VM ID {{ vm_id }}. Signal sent to Camunda."
