---
- name: Change CPU count for a VM
  hosts: localhost
  gather_facts: false
  vars:
    vm_id: null         # Dynamisch übergebene VM-ID
    new_cpu_count: null # Dynamisch übergebene CPU-Anzahl
  tasks:
    - name: Validate input variables
      fail:
        msg: "vm_id and new_cpu_count must be provided"
      when: vm_id is not defined or new_cpu_count is not defined

    - name: Update CPU count in the database
      postgresql_query:
        db: vminventory
        login_user: jonas
        login_password: admin
        query: "UPDATE VMs SET cpu_count = {{ new_cpu_count }} WHERE vm_id = {{ vm_id }}"
      register: result

    - name: Confirm CPU update
      debug:
        msg: "Updated CPU count for VM ID {{ vm_id }} to {{ new_cpu_count }}"

