---
- name: Report on completed process
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display task summary
      debug:
        msg: |
          Completed Process Report:
          {% for change in changes %}
          Task: {{ change.task }}
          Result: {{ change.result }}
          Details: {{ change.details }}
          {% endfor %}

    - name: Check overall process success
      debug:
        msg: "Process completed successfully"
      when: changes | selectattr('result', 'equalto', 'Failed') | list | length == 0

    - name: Indicate process failure
      debug:
        msg: "Process completed with errors"
      when: changes | selectattr('result', 'equalto', 'Failed') | list | length > 0
