---
- name: Report on completed process
  hosts: localhost
  gather_facts: false
  vars:
    changes:
      - { task: "Changed CPU count", result: "Success", details: "CPU count set to 8 for VM ID 1" }
      - { task: "Changed RAM size", result: "Success", details: "RAM size set to 16GB for VM ID 1" }
      - { task: "Added storage", result: "Success", details: "Added a 200GB disk to VM ID 1" }
      - { task: "Added network adapter", result: "Failed", details: "Network adapter addition failed due to permissions" }
  tasks:
    - name: Display task summary
      debug:
        msg: |
          Completed Process Report:
          {% for change in changes %}
          Task: {{ change.task }}
          Result: {{ change.result }}
          Details: {{ change.details }}
          {% endfor %}

    - name: Check overall process success
      debug:
        msg: "Process completed successfully"
      when: changes | selectattr('result', 'equalto', 'Failed') | list | length == 0

    - name: Indicate process failure
      debug:
        msg: "Process completed with errors"
      when: changes | selectattr('result', 'equalto', 'Failed') | list | length > 0
