---
- name: Report on completed process
  hosts: localhost
  gather_facts: false
  vars:
    process_instance_id: "{{ process_instance_id | default('') }}"

  tasks:
    - name: Debug received variables
      debug:
        msg:
          - "✅ Process Instance ID: {{ process_instance_id }}"

    - name: Validate input variables
      fail:
        msg: "❌ process_instance_id must be provided!"
      when: process_instance_id | trim == ""

    - block:
        - name: Indicate process completion
          debug:
            msg: "✅ Process completed successfully!"

        - name: Signal process completion to Camunda
          uri:
            url: "http://10.0.2.15:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "process_completion_completed"
            status_code: 204

      rescue:
        - name: Signal failure to Camunda
          uri:
            url: "http://10.0.2.15:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "process_completion_failed"
            status_code: 204

        - name: Log failure message
          debug:
            msg: "❌ Process completion failed! Sent failure signal to Camunda."
