---
- name: Einfaches Playbook für Testzwecke
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Testausgabe anzeigen
      debug:
        msg: "Das Playbook: \"create_snapshot.yaml\" wurde erfolgreich ausgeführt!"

