---
- name: Restore the last snapshot for a VM
  hosts: localhost
  gather_facts: false
  collections:
    - community.postgresql

  vars:
    vm_id: "{{ vm_id }}"
    process_instance_id: "{{ process_instance_id }}"

  tasks:
    - name: Validate input variables
      fail:
        msg: "vm_id and process_instance_id must be provided"
      when: vm_id is not defined or process_instance_id is not defined

    - block:
        - name: Fetch the latest snapshot for the VM
          community.postgresql.postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            login_host: "10.0.2.15"
            login_port: 5432
            query: |
              SELECT 
                cpu_count, 
                ram_size, 
                disks, 
                adapters
              FROM Snapshots
              WHERE vm_id = {{ vm_id }}
              ORDER BY created_at DESC
              LIMIT 1
          register: snapshot_details

        - name: Validate snapshot existence
          fail:
            msg: "No snapshot found for VM ID {{ vm_id }}"
          when: snapshot_details.query_result | length == 0

        - name: Restore CPU count
          community.postgresql.postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            login_host: "10.0.2.15"
            login_port: 5432
            query: "UPDATE VMs SET cpu_count = {{ snapshot_details.query_result[0].cpu_count }} WHERE vm_id = {{ vm_id }}"

        - name: Restore RAM size
          community.postgresql.postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            login_host: "10.0.2.15"
            login_port: 5432
            query: "UPDATE VMs SET ram_size = {{ snapshot_details.query_result[0].ram_size }} WHERE vm_id = {{ vm_id }}"

        - name: Restore Disks (Delete old, Insert new)
          community.postgresql.postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            login_host: "10.0.2.15"
            login_port: 5432
            query: |
              DELETE FROM Disks WHERE vm_id = {{ vm_id }};
              INSERT INTO Disks (vm_id, disk_id, disk_size)
              SELECT 
                {{ vm_id }}, 
                (d->>'disk_id')::INTEGER, 
                (d->>'disk_size')::INTEGER
              FROM jsonb_array_elements('{{ snapshot_details.query_result[0].disks }}'::jsonb) d;

        - name: Restore Network Adapters (Delete old, Insert new)
          community.postgresql.postgresql_query:
            db: vminventory
            login_user: jonas
            login_password: admin
            login_host: "10.0.2.15"
            login_port: 5432
            query: |
              DELETE FROM Netzwerkadapter WHERE vm_id = {{ vm_id }};
              INSERT INTO Netzwerkadapter (vm_id)
              SELECT {{ vm_id }} FROM generate_series(1, {{ snapshot_details.query_result[0].adapters }});

        - name: Confirm restoration
          debug:
            msg: "Snapshot successfully restored for VM ID {{ vm_id }}"

        - name: Signal successful restoration to Camunda
          uri:
            url: "http://10.0.2.15:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "restore_snapshot_completed"
              processInstanceId: "{{ process_instance_id }}"
            status_code: 204

      rescue:
        - name: Signal failure to Camunda
          uri:
            url: "http://10.0.2.15:8080/engine-rest/message"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              messageName: "restore_snapshot_failed"
              processInstanceId: "{{ process_instance_id }}"
            status_code: 204

        - name: Log failure message
          debug:
            msg: "Snapshot restoration failed for VM ID {{ vm_id }}. Signal sent to Camunda."
