---
- name: Restart the VM system
  hosts: localhost
  gather_facts: false

  vars:
    vm_id: "{{ vm_id }}"
    process_instance_id: "{{ process_instance_id }}"

  tasks:
    - name: Simulate system restart
      debug:
        msg: "System for VM ID {{ vm_id }} has been restarted successfully."

    - name: Debug received variables
      debug:
        msg:
          - "✅ VM ID: {{ vm_id | default('NICHT GESETZT') }}"
          - "✅ Prozess-Instance-ID: {{ process_instance_id | default('NICHT GESETZT') }}"

    - name: Signal successful restart to Camunda
      uri:
        url: "http://10.0.2.15:8080/engine-rest/message"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          messageName: "restart_system_completed"
        status_code: 204
